title: "Few-Shot EuroSAT Within-Domain"
author: "Anne Fouilloux"
copyright: "2026"

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence

repository:
  url: https://github.com/annefou/few-shot-eurosat-within-domain
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_theme_options:
      repository_url: https://github.com/annefou/few-shot-eurosat-within-domain
      use_repository_button: true
      use_issues_button: true
